### ISSUE TITLE
TS01 - Ambient Configuration

### ISSUE THREAD

**Issue by rafaelmakaha** [2019-2-arquitetura-desenho/monitoria-app#1]
## Descrição

Configuração do ambiente da aplicação para inicio do desenvolvimento

## Critérios de aceitação

- [X]  Ambiente deve ser criado usando docker
- [X]  Makefile deve estar configurado com principais comando
- [X]  Comandos devem ser documentados com instruções para desenvolvedores

**Comment by darmsDD** [comment]
Inicialização ocorreu sem problemas.
