### ISSUE TITLE
US04 - Página Inicial

### ISSUE THREAD

**Issue by rjoao** [2019-2-arquitetura-desenho/monitoria-app#29]
## Descrição
Desenvolvimento da Tela Inicial da Aplicação.

## Tarefas
- [x] Adicionar informações.

## Critérios de aceitação
- [x] Fidelidade com o protótipo
- [x] Desempenho aceitável
- [x] Aceitação dos membros da equipe

**Comment by WelisonR** [comment]
Issue fechada pelo PR #32.
