### ISSUE TITLE
US02 - Página de Login

### ISSUE THREAD

**Issue by Ridersk** [2019-2-arquitetura-desenho/monitoria-app#4]
## Descrição

Criação da Tela de Login ou Home Page da aplicação, que consiste na autenticação do usuário na aplicação

## Tarefas

- [x] Input de E-mail e senha
- [x] Adicionar Botões para entrar, criar uma conta e entrar como professor
- [x] Logo da aplicação
- [x] Painel Lateral Esquerdo com apresentação da aplicação
- [x] Requisicao de Login e Cadastro para a api

## Critérios de aceitação

- [x] Fidelidade com o protótipo
- [x] Desempenho aceitável
- [x] Aceitação dos membros da equipe

**Comment by andrelucax** [comment]
Login social foi discutido e a equipe preferiu tirar

**Comment by WelisonR** [comment]
Fechado pelo PR #16.
